### ISSUE TITLE
Tracker for issues in code comments

### ISSUE THREAD

**Issue by pentschev** [rapidsai/ucxx#57]
Various issues are currently commented in code, this aims to track those:

### C++

- [ ] [Ensure it's safe to require GIL in `ucxx::python::Future::~Future()`](https://github.com/rapidsai/ucxx/blob/d6243f237a7684a91b222a3a19ec0174b691f07d/cpp/python/src/python_future.cpp#L29-L33)
- [ ] [Move away from `std::shared_ptr<void>`](https://github.com/rapidsai/ucxx/blob/d6243f237a7684a91b222a3a19ec0174b691f07d/cpp/src/request_tag_multi.cpp#L154-L157)
- [ ] [Handle errors in `ucxx::RequestTagMulti::markCompleted()`](https://github.com/rapidsai/ucxx/blob/d6243f237a7684a91b222a3a19ec0174b691f07d/cpp/src/request_tag_multi.cpp#L161-L163)
- [ ] [Prevent throwing exceptions in `ucxx::RequestTagMulti` callbacks](https://github.com/rapidsai/ucxx/blob/d6243f237a7684a91b222a3a19ec0174b691f07d/cpp/src/request_tag_multi.cpp#L191-L192)
- [ ] [Fix destruction of `ucxx::RequestTagMulti`'s `BufferRequest`](https://github.com/rapidsai/ucxx/blob/d6243f237a7684a91b222a3a19ec0174b691f07d/cpp/src/request_tag_multi.cpp#L63-L70)
- [ ] [Ensure progress thread progresses before checking `ucxx::Worker::tagProbe()`](https://github.com/rapidsai/ucxx/blob/d6243f237a7684a91b222a3a19ec0174b691f07d/cpp/src/worker.cpp#L324-L326)

### Python

- [ ] [Deprecate and remove old exception names](https://github.com/rapidsai/ucxx/blob/d6243f237a7684a91b222a3a19ec0174b691f07d/python/ucxx/_lib/libucxx.pyx#L187-L190)
- [ ] [Replace `unique_ptr` by stack object](https://github.com/rapidsai/ucxx/blob/d6243f237a7684a91b222a3a19ec0174b691f07d/python/ucxx/_lib/libucxx.pyx#L224-L227)
- [ ] [Use `cdef enum class` after moving to Cython 3.x](https://github.com/rapidsai/ucxx/blob/d6243f237a7684a91b222a3a19ec0174b691f07d/python/ucxx/_lib/ucxx_api.pxd#L148-L152), similarly [here](https://github.com/rapidsai/ucxx/blob/d6243f237a7684a91b222a3a19ec0174b691f07d/python/ucxx/_lib/ucxx_api.pxd#L172-L176)

### Python tests and benchmarks

- [ ] [Add back custom `UCXCanceledError` message](https://github.com/rapidsai/ucxx/blob/d6243f237a7684a91b222a3a19ec0174b691f07d/python/ucxx/_lib_async/tests/test_endpoint.py#L88-L91), if it's worth the effort
- [ ] [Remove "Message truncated" match when Python futures accept custom exception messages](https://github.com/rapidsai/ucxx/blob/d6243f237a7684a91b222a3a19ec0174b691f07d/python/ucxx/_lib_async/tests/test_send_recv.py#L132-L133)
- [ ] [Fix broken wireup message](https://github.com/rapidsai/ucxx/blob/d6243f237a7684a91b222a3a19ec0174b691f07d/python/ucxx/benchmarks/backends/ucxx_core.py#L29-L31)
- [ ] [Find root cause for hang in `Queue.get()` and fix](https://github.com/rapidsai/ucxx/blob/d6243f237a7684a91b222a3a19ec0174b691f07d/python/ucxx/benchmarks/backends/ucxx_core.py#L152-L154)

### C++ Tests

- [ ] [Use a timeout when probing for tags](https://github.com/rapidsai/ucxx/blob/d6243f237a7684a91b222a3a19ec0174b691f07d/cpp/tests/worker.cpp#L84-L87)

### CMake

- [ ] [Do not require C module to build Python extensions](https://github.com/rapidsai/ucxx/blob/d6243f237a7684a91b222a3a19ec0174b691f07d/python/CMakeLists.txt#L15-L18)
- [ ] [Remove find NumPy workaround](https://github.com/rapidsai/ucxx/blob/d6243f237a7684a91b222a3a19ec0174b691f07d/python/ucxx/_lib/CMakeLists.txt#L15-L18)

### Build scripts

- [ ] [Fix defaults for variables that are not externally defined (maybe raise fatal error?)](https://github.com/rapidsai/ucxx/blob/d6243f237a7684a91b222a3a19ec0174b691f07d/build.sh#L58-L62), taken [from cudf](https://github.com/rapidsai/cudf/blob/3e32dc3e2b869db0286dd79662c581258fa5b14f/build.sh#L73-L77)
